package com.hybridata.revisegpt.domain;

import static com.hybridata.revisegpt.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ChatHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatHistoryAllPropertiesEquals(ChatHistory expected, ChatHistory actual) {
        assertChatHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertChatHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatHistoryAllUpdatablePropertiesEquals(ChatHistory expected, ChatHistory actual) {
        assertChatHistoryUpdatableFieldsEquals(expected, actual);
        assertChatHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatHistoryAutoGeneratedPropertiesEquals(ChatHistory expected, ChatHistory actual) {
        assertThat(expected)
            .as("Verify ChatHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatHistoryUpdatableFieldsEquals(ChatHistory expected, ChatHistory actual) {
        assertThat(expected)
            .as("Verify ChatHistory relevant properties")
            .satisfies(e -> assertThat(e.getPrompt()).as("check prompt").isEqualTo(actual.getPrompt()))
            .satisfies(e -> assertThat(e.getGeneratedResponse()).as("check generatedResponse").isEqualTo(actual.getGeneratedResponse()))
            .satisfies(e -> assertThat(e.getTokenUsage()).as("check tokenUsage").isEqualTo(actual.getTokenUsage()))
            .satisfies(e -> assertThat(e.getResponseTimeMs()).as("check responseTimeMs").isEqualTo(actual.getResponseTimeMs()))
            .satisfies(e -> assertThat(e.getFeedbackRating()).as("check feedbackRating").isEqualTo(actual.getFeedbackRating()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatHistoryUpdatableRelationshipsEquals(ChatHistory expected, ChatHistory actual) {
        assertThat(expected)
            .as("Verify ChatHistory relationships")
            .satisfies(e -> assertThat(e.getSession()).as("check session").isEqualTo(actual.getSession()));
    }
}
