package com.hybridata.revisegpt.domain;

import static com.hybridata.revisegpt.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CourseHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseHistoryAllPropertiesEquals(CourseHistory expected, CourseHistory actual) {
        assertCourseHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertCourseHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseHistoryAllUpdatablePropertiesEquals(CourseHistory expected, CourseHistory actual) {
        assertCourseHistoryUpdatableFieldsEquals(expected, actual);
        assertCourseHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseHistoryAutoGeneratedPropertiesEquals(CourseHistory expected, CourseHistory actual) {
        assertThat(expected)
            .as("Verify CourseHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseHistoryUpdatableFieldsEquals(CourseHistory expected, CourseHistory actual) {
        assertThat(expected)
            .as("Verify CourseHistory relevant properties")
            .satisfies(e -> assertThat(e.getGeneratedResponse()).as("check generatedResponse").isEqualTo(actual.getGeneratedResponse()))
            .satisfies(e -> assertThat(e.getGeneratedFileUrl()).as("check generatedFileUrl").isEqualTo(actual.getGeneratedFileUrl()))
            .satisfies(e -> assertThat(e.getInputFileUrl()).as("check inputFileUrl").isEqualTo(actual.getInputFileUrl()))
            .satisfies(e -> assertThat(e.getTokenUsage()).as("check tokenUsage").isEqualTo(actual.getTokenUsage()))
            .satisfies(e -> assertThat(e.getResponseTimeMs()).as("check responseTimeMs").isEqualTo(actual.getResponseTimeMs()))
            .satisfies(e -> assertThat(e.getFeedbackRating()).as("check feedbackRating").isEqualTo(actual.getFeedbackRating()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseHistoryUpdatableRelationshipsEquals(CourseHistory expected, CourseHistory actual) {
        assertThat(expected)
            .as("Verify CourseHistory relationships")
            .satisfies(e -> assertThat(e.getSession()).as("check session").isEqualTo(actual.getSession()));
    }
}
