package com.hybridata.revisegpt.domain;

import static com.hybridata.revisegpt.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class KnowledgeBaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeBaseAllPropertiesEquals(KnowledgeBase expected, KnowledgeBase actual) {
        assertKnowledgeBaseAutoGeneratedPropertiesEquals(expected, actual);
        assertKnowledgeBaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeBaseAllUpdatablePropertiesEquals(KnowledgeBase expected, KnowledgeBase actual) {
        assertKnowledgeBaseUpdatableFieldsEquals(expected, actual);
        assertKnowledgeBaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeBaseAutoGeneratedPropertiesEquals(KnowledgeBase expected, KnowledgeBase actual) {
        assertThat(expected)
            .as("Verify KnowledgeBase auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeBaseUpdatableFieldsEquals(KnowledgeBase expected, KnowledgeBase actual) {
        assertThat(expected)
            .as("Verify KnowledgeBase relevant properties")
            .satisfies(e -> assertThat(e.getFileName()).as("check fileName").isEqualTo(actual.getFileName()))
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getEmbed()).as("check embed").isEqualTo(actual.getEmbed()))
            .satisfies(e -> assertThat(e.getVectorId()).as("check vectorId").isEqualTo(actual.getVectorId()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e ->
                assertThat(e.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdatedAt())
            )
            .satisfies(e -> assertThat(e.getFileUrl()).as("check fileUrl").isEqualTo(actual.getFileUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeBaseUpdatableRelationshipsEquals(KnowledgeBase expected, KnowledgeBase actual) {
        // empty method
    }
}
