package com.hybridata.revisegpt.domain;

import static com.hybridata.revisegpt.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class SessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAllPropertiesEquals(Session expected, Session actual) {
        assertSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAllUpdatablePropertiesEquals(Session expected, Session actual) {
        assertSessionUpdatableFieldsEquals(expected, actual);
        assertSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAutoGeneratedPropertiesEquals(Session expected, Session actual) {
        assertThat(expected)
            .as("Verify Session auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionUpdatableFieldsEquals(Session expected, Session actual) {
        assertThat(expected)
            .as("Verify Session relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getSessionStatus()).as("check sessionStatus").isEqualTo(actual.getSessionStatus()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e ->
                assertThat(e.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdatedAt())
            )
            .satisfies(e ->
                assertThat(e.getEndedAt()).as("check endedAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getEndedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionUpdatableRelationshipsEquals(Session expected, Session actual) {
        // empty method
    }
}
